name: Run Hive Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  run-hive-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Hive bot
      env:
        HIVE_USERNAME: ${{ secrets.HIVE_USERNAME }}
        POSTING_KEY: ${{ secrets.POSTING_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python main.py
